name: Run Naukri Update Test Every 30 Mins from 6 AM IST

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0,30 * * * *'  # Every 30 minutes
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
               path: ~/.m2
               key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
               restore-keys: ${{ runner.os }}-maven

      - name: Install XVFB and Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 &

      - name: Run Tests (non-headless Chrome)
        run: |
          export DISPLAY=:99
          mvn clean install -DsuiteXmlFile=testng.xml
      # - name: Set up Chrome
      #   uses: browser-actions/setup-chrome@v1

     

      # - name: Run NaukriUpdate.xml tests
      #   run: mvn clean install -DsuiteXmlFile=testng.xml
